---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-system-vault
  namespace: flux-system
  labels:
    app: flux-system
    component: vault-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-system-vault-auth-binding
  labels:
    app: flux-system
    component: vault-auth
subjects:
  - kind: ServiceAccount
    name: flux-system-vault
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: preview-environments
  namespace: flux-system
  labels:
    app: flux-system
    component: preview-environments
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: preview-environments-dev
  namespace: dev
rules:
- apiGroups:
  - kustomize.toolkit.fluxcd.io
  resources:
  - kustomizations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: preview-environments-dev
  namespace: dev
subjects:
- kind: ServiceAccount
  name: preview-environments
  namespace: flux-system
roleRef:
  kind: Role
  name: preview-environments-dev
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: preview-environments-cluster
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: preview-environments-cluster
subjects:
- kind: ServiceAccount
  name: preview-environments
  namespace: flux-system
roleRef:
  kind: ClusterRole
  name: preview-environments-cluster
  apiGroup: rbac.authorization.k8s.io
