---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: openbao
  namespace: flux-system
spec:
  address: https://openbao.homelab.haseebmajid.dev
  skipTLSVerify: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: flux-system
  namespace: flux-system
spec:
  vaultConnectionRef: openbao
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: k8s-auth-role
    serviceAccount: flux-system-vault
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: gitlab-api-secret
  namespace: flux-system
spec:
  vaultAuthRef: flux-system
  mount: kv
  type: kv-v2
  path: apps/gitlab
  destination:
    name: gitlab-api-token
    create: true
    transformation:
      templates:
        token:
          text: "{{ .Secrets.webhook_token }}"
        username:
          text: "{{ .Secrets.username }}"
        password:
          text: "{{ .Secrets.password }}"
        webhook_token:
          text: "{{ .Secrets.webhook_token }}"
  refreshAfter: 10m
