---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gitlab-api-secret
  namespace: flux-system
spec:
  provider: vault
  parameters:
    vaultAddress: "http://openbao.vault-system.svc.cluster.local:8200"
    roleName: "flux-system-role"
    objects: |
      - objectName: "gitlab-token"
        secretPath: "kv/data/apps/gitlab"
        secretKey: "token"
      - objectName: "gitlab-webhook-token"
        secretPath: "kv/data/apps/gitlab"
        secretKey: "webhook_token"
  secretObjects:
  - secretName: gitlab-api-credentials
    type: Opaque
    data:
    - objectName: gitlab-token
      key: token
    - objectName: gitlab-webhook-token
      key: webhook_token
---
# Deployment to mount the secret (required for CSI driver)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab-secret-provider
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab-secret-provider
  template:
    metadata:
      labels:
        app: gitlab-secret-provider
    spec:
      serviceAccountName: flux-system-vault
      containers:
      - name: busybox
        image: busybox:1.35
        command: ['sleep', '3600']
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets"
          readOnly: true
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 20m
            memory: 32Mi
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "gitlab-api-secret"
