---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  type: kv-v2
  mount: kv
  path: infra/tailscale
  destination:
    name: operator-oauth
    create: true
  refreshAfter: 24h
  vaultAuthRef: dev/openbao
