---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale
  labels:
    app: tailscale
subjects:
- kind: ServiceAccount
  name: tailscale
  namespace: tailscale
roleRef:
  kind: ClusterRole
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
