---
# Using Vault Secrets Operator to pull secret from OpenBao
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tailscale-auth
  namespace: tailscale
spec:
  type: kv-v2
  # Vault connection reference
  vaultAuthRef: tailscale/vault-auth
  # Path in OpenBao where the secret is stored
  mount: kv
  path: infra/tailscale
  # How often to refresh the secret
  refreshAfter: 3600s
  # Destination secret
  destination:
    name: tailscale-auth
    create: true
    transformation:
      templates:
        TS_AUTHKEY:
          text: "{{ .Secrets.AUTH_KEY }}"