---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: flux-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: flux-operator
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
  values:
    # Enable ResourceSets for GitLab integration
    resourceSets:
      enabled: true

    # Controller configuration
    controller:
      resources:
        limits:
          cpu: 200m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi

    # RBAC configuration
    rbac:
      create: true

    # Service account
    serviceAccount:
      create: true
      name: flux-operator

    # Webhook configuration
    webhook:
      enabled: true
      port: 9443
      service:
        type: ClusterIP
        port: 9443
