---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: flux-operator
      version: ">=0.28.0"
      sourceRef:
        kind: HelmRepository
        name: controlplane-flux
        namespace: flux-system
      interval: 12h
  install:
    createNamespace: false
  values:
    # Enable ResourceSets for GitLab integration
    resourceSets:
      enabled: true

    # Controller configuration
    controller:
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi

    # RBAC configuration
    rbac:
      create: true

    # Service account
    serviceAccount:
      create: true
      name: flux-operator

    # Enable webhook for faster reconciliation
    webhook:
      enabled: true
