---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mirrord-operator
  namespace: mirrord
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mirrord-operator
rules:
- apiGroups: [""]
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs: ["*"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs: ["*"]
- apiGroups: ["monitoring.coreos.com"]
  resources:
  - servicemonitors
  verbs: ["get", "create"]
- apiGroups: ["apps"]
  resources:
  - deployments/finalizers
  verbs: ["update"]
- apiGroups: [""]
  resources:
  - pods/log
  - pods/exec
  verbs: ["*"]
- apiGroups: ["operator.metalbear.co"]
  resources:
  - "*"
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mirrord-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mirrord-operator
subjects:
- kind: ServiceAccount
  name: mirrord-operator
  namespace: mirrord
---
# Additional RBAC for dev namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mirrord-dev-access
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mirrord-operator
subjects:
- kind: ServiceAccount
  name: mirrord-operator
  namespace: mirrord
---
# Additional RBAC for prod namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mirrord-prod-access
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mirrord-operator
subjects:
- kind: ServiceAccount
  name: mirrord-operator
  namespace: mirrord
