---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tailscale-simple
  namespace: tailscale
  labels:
    app: tailscale
    variant: simple
spec:
  selector:
    matchLabels:
      app: tailscale
      variant: simple
  template:
    metadata:
      labels:
        app: tailscale
        variant: simple
    spec:
      serviceAccountName: tailscale
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: tailscale
          image: tailscale/tailscale:v1.76.6
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: authkey
            - name: TS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: TS_ROUTES
              value: "10.42.0.0/16,10.43.0.0/16"
            - name: TS_ACCEPT_DNS
              value: "true"
            - name: TS_EXTRA_ARGS
              value: >-
                --advertise-routes=$(TS_ROUTES) --accept-routes
                --hostname=$(TS_HOSTNAME)-k8s
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
      tolerations:
        - operator: Exists
          effect: NoSchedule
