apiVersion: v1
kind: Namespace
metadata:
  name: vault-secrets-operator-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: vault-secrets-operator-system
spec:
  interval: 1h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator-system
spec:
  interval: 1h
  chart:
    spec:
      chart: vault-secrets-operator
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault-secrets-operator-system
      version: "*"
  values:
    defaultVaultConnection:
      enabled: true
      address: "https://openbao.homelab.haseebmajid.dev"
      skipTLSVerify: true
