---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-agent
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: monitoring
      interval: 12h
  install:
    createNamespace: true
  values:
    # Deploy as DaemonSet to collect from all nodes
    mode: daemonset

    serviceAccount:
      create: false
      name: otel-agent

    # Lightweight agent configuration - forward only
    config:
      receivers:
        # Kubernetes cluster metrics via API server
        k8s_cluster:
          collection_interval: 30s
          node_conditions_to_report: [Ready, MemoryPressure, DiskPressure, PIDPressure]
          allocatable_types_to_report: [cpu, memory, storage, ephemeral-storage]

        # Kubelet metrics from each node
        kubeletstats:
          collection_interval: 30s
          auth_type: "serviceAccount"
          endpoint: "${env:K8S_NODE_NAME}:10250"
          insecure_skip_verify: true

        # Kubernetes events as logs
        k8sobjects:
          auth_type: serviceAccount
          objects:
            - name: events
              mode: watch
              group: events.k8s.io
              exclude_watch_type: [DELETED]

        # Container logs via filelog receiver
        filelog:
          include:
            - /var/log/pods/*/*/*.log
          exclude:
            # Exclude OTEL agent's own logs to prevent loops
            - /var/log/pods/monitoring_otel-agent-*/*/*.log
            # Exclude system pods that are too noisy
            - /var/log/pods/kube-system_*/*/*.log
          include_file_name: false
          include_file_path: true
          operators:
            # Parse container logs
            - type: json_parser
              id: parser-docker
              output: extract_metadata_from_filepath
              timestamp:
                parse_from: attributes.time
                layout: '%Y-%m-%dT%H:%M:%S.%LZ'
            # Extract pod metadata from file path
            - type: regex_parser
              id: extract_metadata_from_filepath
              regex: '^.*\/(?P<namespace>[^_]+)_(?P<pod_name>[^_]+)_(?P<uid>[a-f0-9\-]+)\/(?P<container_name>[^\._]+)\/(?P<restart_count>\d+)\.log$'
              parse_from: attributes["log.file.path"]
              output: add_attributes
            # Add Kubernetes attributes
            - type: add
              id: add_attributes
              field: attributes.k8s.namespace.name
              value: EXPR(attributes.namespace)
            - type: add
              field: attributes.k8s.pod.name
              value: EXPR(attributes.pod_name)
            - type: add
              field: attributes.k8s.container.name
              value: EXPR(attributes.container_name)
            - type: add
              field: attributes.k8s.pod.uid
              value: EXPR(attributes.uid)

        # Scrape kube-state-metrics
        prometheus:
          config:
            global:
              scrape_interval: 30s
            scrape_configs:
              # Scrape kube-state-metrics
              - job_name: 'kube-state-metrics'
                static_configs:
                  - targets: ['kube-state-metrics.monitoring.svc.cluster.local:8080']
                scrape_interval: 30s
                metrics_path: '/metrics'

              # Scrape kubelet cadvisor metrics
              - job_name: 'kubelet-cadvisor'
                kubernetes_sd_configs:
                  - role: node
                scheme: https
                tls_config:
                  ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                  insecure_skip_verify: true
                bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                relabel_configs:
                  - action: labelmap
                    regex: __meta_kubernetes_node_label_(.+)
                  - target_label: __address__
                    replacement: kubernetes.default.svc:443
                  - source_labels: [__meta_kubernetes_node_name]
                    regex: (.+)
                    target_label: __metrics_path__
                    replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor

              # Scrape node metrics from kubelet
              - job_name: 'kubelet'
                kubernetes_sd_configs:
                  - role: node
                scheme: https
                tls_config:
                  ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                  insecure_skip_verify: true
                bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
                relabel_configs:
                  - action: labelmap
                    regex: __meta_kubernetes_node_label_(.+)
                  - target_label: __address__
                    replacement: kubernetes.default.svc:443
                  - source_labels: [__meta_kubernetes_node_name]
                    regex: (.+)
                    target_label: __metrics_path__
                    replacement: /api/v1/nodes/$1/proxy/metrics

      processors:
        # Add Kubernetes metadata
        k8sattributes:
          auth_type: "serviceAccount"
          passthrough: false
          filter:
            node_from_env_var: K8S_NODE_NAME
          extract:
            metadata:
              - k8s.pod.name
              - k8s.pod.uid
              - k8s.deployment.name
              - k8s.namespace.name
              - k8s.node.name
              - k8s.pod.start_time
          pod_association:
            - sources:
              - from: resource_attribute
                name: k8s.pod.ip
            - sources:
              - from: resource_attribute
                name: k8s.pod.uid
            - sources:
              - from: connection

        # Add resource attributes
        resource:
          attributes:
            - key: k8s.cluster.name
              value: "homelab"
              action: upsert
            - key: deployment.environment
              value: "production"
              action: upsert
            - key: service.name
              value: "k8s-cluster"
              action: upsert

        # Batch processing for efficiency
        batch:
          timeout: 10s
          send_batch_size: 1024

      exporters:
        # Export to your existing OTEL collector
        otlphttp:
          endpoint: "https://otel-collector.homelab.haseebmajid.dev"
          headers:
            "X-Source": "k8s-cluster"
            "X-Cluster": "homelab"
          compression: gzip
          timeout: 30s
          retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_interval: 30s
            max_elapsed_time: 300s

      service:
        telemetry:
          logs:
            level: info
          metrics:
            address: 0.0.0.0:8888

        pipelines:
          # Metrics pipeline - forward to remote collector
          metrics:
            receivers: [k8s_cluster, kubeletstats, prometheus]
            processors: [k8sattributes, resource, batch]
            exporters: [otlphttp]

          # Logs pipeline - forward container logs and events
          logs:
            receivers: [filelog, k8sobjects]
            processors: [k8sattributes, resource, batch]
            exporters: [otlphttp]

    # Minimal resource usage for agent
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi

    nodeSelector:
      kubernetes.io/os: linux

    tolerations:
      - operator: Exists
        effect: NoSchedule
      - operator: Exists
        effect: NoExecute

    env:
      - name: K8S_NODE_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName

    # Mount host log directories for log collection
    extraVolumes:
      - name: varlogpods
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers

    extraVolumeMounts:
      - name: varlogpods
        mountPath: /var/log/pods
        readOnly: true
      - name: varlibdockercontainers
        mountPath: /var/lib/docker/containers
        readOnly: true
      - name: varlogcontainers
        mountPath: /var/log/containers
        readOnly: true
