---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: banterbus-dev
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infra/k8s/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: banterbus-source
  targetNamespace: dev
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: banterbus
      namespace: dev
  dependsOn:
    - name: flux-system
