---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bugsink
  namespace: prod
spec:
  interval: 30m
  chart:
    spec:
      chart: bugsink
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bugsink
        namespace: prod
      interval: 12h
  install:
    createNamespace: false
  values:
    # Base URL for Bugsink
    baseUrl: "https://bugsink.haseebmajid.dev"

    # Image configuration
    image:
      repository: bugsink/bugsink
      tag: latest
      pullPolicy: IfNotPresent

    # Service configuration
    service:
      type: ClusterIP
      port: 8000

    # Ingress configuration - disabled as we use Cloudflare tunnel
    ingress:
      enabled: false

    # Resource limits and requests
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

    # Environment variables using secrets from OpenBao
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: bugsink-secrets
            key: secret_key
      - name: CREATE_SUPERUSER
        value: "admin:admin"
      - name: PORT
        value: "8000"
      # Database configuration - using external PostgreSQL
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: bugsink-secrets
            key: database_url
      # Configure snappea task queue for containerized environment
      - name: DIGEST_IMMEDIATELY
        value: "True"
      - name: TASK_ALWAYS_EAGER
        value: "True"
      - name: SNAPPEA_DATABASE_PATH
        value: "/tmp/snappea.db"

    # Disable built-in PostgreSQL
    postgresql:
      enabled: false

    # Use external PostgreSQL database
    externalDatabase:
      existingSecret: bugsink-secrets
      existingSecretKey: database_url

    # Autoscaling
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80

    # Node selector and tolerations
    nodeSelector: {}
    tolerations: []
    affinity: {}
