---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bugsink
  namespace: prod
spec:
  interval: 30m
  chart:
    spec:
      chart: bugsink
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bugsink
        namespace: prod
      interval: 12h
  install:
    createNamespace: false
  values:
    # Base URL for Bugsink
    baseUrl: "https://bugsink.haseebmajid.dev"

    # Image configuration
    image:
      repository: bugsink/bugsink
      tag: latest
      pullPolicy: IfNotPresent

    # Service configuration
    service:
      type: ClusterIP
      port: 8000

    # Ingress configuration - disabled as we use Cloudflare tunnel
    ingress:
      enabled: false

    # Resource limits and requests
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

    # Environment variables using secrets from OpenBao
    env:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: bugsink-secrets
            key: secret_key
      - name: CREATE_SUPERUSER
        value: "admin:admin"
      - name: PORT
        value: "8000"
      # Database configuration - using external PostgreSQL
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: bugsink-secrets
            key: database_url
      # Configure snappea task queue for containerized environment
      - name: DIGEST_IMMEDIATELY
        value: "True"
      - name: TASK_ALWAYS_EAGER
        value: "True"
      - name: SNAPPEA_DATABASE_PATH
        value: "/tmp/snappea.db"

    # Disable built-in PostgreSQL
    postgresql:
      enabled: false

    # Pod security context - run as root for SQLite write permissions
    securityContext:
      runAsNonRoot: false
      runAsUser: 0
      fsGroup: 0

    # Container security context
    containerSecurityContext:
      runAsUser: 0

    # Init containers for snappea database initialization
    initContainers:
      - name: snappea-init
        image: bugsink/bugsink:latest
        command: ["/bin/bash", "-c", "bugsink-manage migrate --database=snappea"]
        envFrom:
          - secretRef:
              name: bugsink
          - configMapRef:
              name: bugsink
        volumeMounts:
          - name: tmp-data
            mountPath: /tmp

    # Add volumes for writable SQLite databases
    extraVolumes:
      - name: tmp-data
        emptyDir: {}

    extraVolumeMounts:
      - name: tmp-data
        mountPath: /tmp

    # Autoscaling
    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80

    # Node selector and tolerations
    nodeSelector: {}
    tolerations: []
    affinity: {}
