---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: bugsink-secrets
  namespace: prod
spec:
  type: kv-v2
  mount: kv
  path: apps/bugsink
  destination:
    name: bugsink-secrets
    create: true
  refreshAfter: 24h
  vaultAuthRef: prod/openbao
