---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flagger
  namespace: flagger-system
spec:
  interval: 30m
  chart:
    spec:
      chart: flagger
      version: "1.39.0"
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    meshProvider: traefik
    metricsServer: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    slack:
      url: ""
      channel: ""
      username: flagger
    msteams:
      url: ""
    leaderElection:
      enabled: true
    resources:
      limits:
        memory: "512Mi"
        cpu: "1000m"
      requests:
        memory: "32Mi"
        cpu: "10m"
