---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: prod
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: prod
      interval: 12h
  install:
    createNamespace: false
  values:
    # Use existing service account
    serviceAccount:
      create: false
      name: headlamp

    # Enable in-cluster mode
    config:
      oidc:
        enabled: false
      baseURL: ""

    # Resource configuration
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi

    # Service configuration - NodePort for host access
    service:
      type: NodePort
      port: 80
      nodePort: 30080

    # Enable persistence for plugins
    persistence:
      enabled: true
      size: 1Gi
      storageClass: ""

    # Plugin configuration - using sidecar approach
    plugins:
      enabled: true

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 100
      runAsGroup: 101

    # Node selection
    nodeSelector: {}
    tolerations: []
    affinity: {}
