---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: prod
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/component: admin-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/component: admin-service-account
subjects:
  - kind: ServiceAccount
    name: headlamp-admin
    namespace: prod
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: headlamp-admin-token
  namespace: prod
  labels:
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/component: admin-service-account
  annotations:
    kubernetes.io/service-account.name: headlamp-admin
type: kubernetes.io/service-account-token
