apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitlab-agent
  namespace: gitlab-agent-k8s
spec:
  interval: 30m
  chart:
    spec:
      chart: gitlab-agent
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab-agent-k8s
      interval: 12h
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: gitlab-agent-token
      valuesKey: agent-token
      targetPath: config.token
  values:
    config:
      kasAddress: "wss://kas.gitlab.com"
