---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare-tunnel
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cloudflare-tunnel
      interval: 12h
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: cloudflare-tunnel-token
      valuesKey: token
      targetPath: cloudflare.tunnel_token
  values:
    # Token-based remote-managed tunnel: "k8s"
    # Configure ingress rules via Cloudflare dashboard
    replicaCount: 2
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi