---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare-tunnel
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cloudflare-tunnel
      interval: 12h
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: cloudflare-tunnel-token
      valuesKey: account-id
      targetPath: cloudflare.account
    - kind: Secret
      name: cloudflare-tunnel-token
      valuesKey: tunnel-id
      targetPath: cloudflare.tunnelId
    - kind: Secret
      name: cloudflare-tunnel-token
      valuesKey: tunnel-secret
      targetPath: cloudflare.secret
  values:
    cloudflare:
      # Kubernetes-managed tunnel configuration
      tunnelName: "k8s"
      secretName: "cloudflare-tunnel-token"
      ingress:
        # Default catch-all rule - returns 404 for all traffic
        - service: http_status:404
    replicaCount: 2
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi