---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-tunnel
  namespace: cloudflare-tunnel
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-tunnel-remote
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cloudflare-tunnel
      interval: 12h
  install:
    createNamespace: true
  valuesFrom:
    - kind: Secret
      name: cloudflare-tunnel-token
      valuesKey: tunnel_token
      targetPath: cloudflare.tunnel_token
  values:
    tunnelTokenSecretName: cloudflare-tunnel-token
    tunnelTokenSecretKey: tunnel_token
    existingSecret: cloudflare-tunnel-token
    args:
      - tunnel
      - run
      - --config
      - /etc/cloudflared/config/config.yaml
      - k8s-gitops-tunnel
    extraVolumeMounts:
      - name: config
        mountPath: /etc/cloudflared/config
        readOnly: true
      - name: creds
        mountPath: /etc/cloudflared/creds
        readOnly: true
    extraVolumes:
      - name: config
        configMap:
          name: cloudflare-tunnel-config
      - name: creds
        secret:
          secretName: cloudflare-tunnel-creds
    replicaCount: 2
    resources:
      limits:
        cpu: 200m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
