---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  type: kv-v2
  mount: kv
  path: infra/cloudflare
  destination:
    name: cloudflare-tunnel-credentials
    create: true
    transformation:
      templates:
        credentials.json:
          text: |
            {
              "AccountTag": "{{ get .Secrets "account_id" }}",
              "TunnelID": "{{ get .Secrets "tunnel_id" }}",
              "TunnelSecret": "{{ b64enc (get .Secrets "tunnel_secret") }}"
            }
  refreshAfter: 24h
  vaultAuthRef: cloudflare-tunnel/openbao
