---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-tunnel-creds
  namespace: cloudflare-tunnel
spec:
  type: kv-v2
  mount: kv
  path: infra/cloudflare
  destination:
    name: cloudflare-tunnel-creds
    create: true
  refreshAfter: 24h
  vaultAuthRef: cloudflare-tunnel/openbao
