---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  type: kv-v2
  mount: kv
  path: infra/cloudflare-tunnel
  destination:
    name: cloudflare-tunnel-credentials
    create: true
  refreshAfter: 24h
  vaultAuthRef: dev/openbao